# Generated by Django 3.2.13 on 2022-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=250)),
                ('st_tugas', models.CharField(choices=[(0, 'Tidak Aktif'), (1, 'Aktif'), (2, 'Dalam Proses'), (3, 'Selesai'), (4, 'Batal')], default=0, max_length=2)),
            ],
        ),
    ]
