# Generated by Django 3.2.13 on 2022-05-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugasan',
            name='st_tugas',
            field=models.CharField(choices=[('0', 'Tidak Aktif'), ('1', 'Aktif'), ('2', 'Dalam Proses'), ('3', 'Selesai'), ('4', 'Batal')], default=0, max_length=2),
        ),
    ]
